# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  repository_dispatch:
    types: test-dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
      - uses: echo hello
