# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  repository_dispatch:
    types: deploy-to-prod

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: rsync -a testing/. "${{ secrets.ADDRESS }}":~/views/admin/test
